name: Cleanup Merged Branch

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  delete-branch:
    name: Delete merged branch
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.REPO_DELETE_BRANCH_SECRET }}