name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy on Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull the Docker image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/rest-api:latest

      - name: SSH and Deploy Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SECRET }} #ssh key
          script: |
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/rest-api:latest